In [7]:
import numpy as np
M = np.array([
              [5, 3, 0, 1],
              [4, 0, 0, 1],
              [1, 1, 0, 5],
              [1, 0, 0, 4],
              [0, 1, 5, 4],
                ])
#function func1(A) use to caculate average of value #0 in matrix
def func1(A):
    num_user = A.shape[0]
    num_item = A.shape[1]
    count= 0  
    summ=0
    for u in range(num_user):
        for i in range(num_item):
            if(A[u,i]>0):
                summ += A[u,i]
                count +=1
                
    mediaSum = summ/count
    return mediaSum
####
# function caculate(A,num1,num2) use to caculate b_u(u), b_i(i)
def caculate(A, num1, num2):
    b = np.zeros((num1))
    for u in range(0,num1):
        summ=0.
        count_b=0 
        for i in range(0,num2):
            if(A[u,i]>0):
                summ+=   A[u,i]-func1(A) 
                count_b+=1
        b[u] = summ/(count_b)  
    return b
# number rows, columns
u=M.shape[0]
i=M.shape[1]
# assign b_u, b_i
b_u=caculate(M,u,i)
b_i=caculate(M.T,i,u)
#b_ii = caculate_i(M,u,i)
print("=============================================================================")
print("---CÁC GIÁ TRỊ BAN ĐẦU-------")
print("=============================================================================")
print("---Trung bình cộng ma trận---")
print(func1(M))
print("---b_u---")
print(b_u)
print("---b_i---")
print(b_i)
print("=============================================================================")
#print(b_ii)

#function MF(A,K,b,iteration,lamda) use MF bias 
def MF(A,K,b,iteration, lamda):
    U=A.shape[0]
    I=A.shape[1]
    
    W = np.random.randn(U,K)
    H = np.random.randn(K,I)
    step=0
    m1 = func1(M)
    while step<iteration:
        for u in range(U):
            for i in range(I):
                if(A[u,i]>0):
                    
                    r =  m1 + b_u[u] + b_i[i]
                    for k in range(K):
                        r +=np.dot(W[u,k],H[k,i])
                    e = A[u,i] - r
                    m1 += b*e
                    b_u[u]+= b*(e-lamda*b_u[u])
                    b_i[i]+= b*(e-lamda*b_i[i])
                                
                    for k in range(K):
                        W[u,k] +=  b*(2*e * H[k,i] - lamda*W[u,k])
                        H[k,i] +=  b*(2*e * W[u,k] - lamda*H[k,i])
        step+=1
    
                        
    return m1 + b_u[:,np.newaxis] +b_i[np.newaxis:,] + np.dot(W,H), b_u, b_i, m1, W, H
X,m_u,m_i, m,w,h =MF(M,2,0.01,500,0.01)
print("=============================================================================")
print("---KẾT QUẢ---")
print("=============================================================================")
print("-----Ma trận W-------")
print(w)
print("-----Ma trận H-------")
print(h)
print("---b_u_update---")
print(m_u)
print("---b_i_update---")
print(m_i)
print("---Tổng ma trận update---")
print(m)
print("=============================================================================")
print("---Ma trận ban đầu---")
print(M)
print("---Ma trận dự đoán ---")
print(X)
print("---Ma trận dự đoán làm tròn---")
print(np.around(X))


                    
        
        

---CÁC GIÁ TRỊ BAN ĐẦU-------
---Trung bình cộng ma trận---
2.769230769230769
---b_u---
[ 0.23076923 -0.26923077 -0.43589744 -0.26923077  0.56410256]
---b_i---
[-0.01923077 -1.1025641   2.23076923  0.23076923]
---KẾT QUẢ---
-----Ma trận W-------
[[-1.24447832  0.69186576]
 [-0.79025528  0.71643546]
 [ 1.05164455 -0.72985976]
 [ 0.44065942 -0.94128643]
 [ 0.38398072  0.9228992 ]]
-----Ma trận H-------
[[-0.24733345 -0.92855575  0.10803202  2.04159955]
 [ 1.54673411 -0.95541914 -0.70851536 -0.36222736]]
---b_u_update---
[ 0.6736418  -0.24786522 -0.54654777 -0.36968062  0.4215921 ]
---b_i_update---
[ 0.03535156 -1.07609596  2.27788617  0.22033181]
---Tổng ma trận update---
2.9055817883648762
---Ma trận ban đầu---
[[5 3 0 1]
 [4 0 0 1]
 [1 1 0 5]
 [1 0 0 4]
 [0 1 5 4]]
---Ma trận dự đoán ---
[[4.99250864 2.99767334 5.23246874 1.0082163 ]
 [3.99665986 1.63092053 4.34262434 1.00515103]
 [1.00537972 1.00374945 5.26764832 4.99077805]
 [1.00634309 1.94995144 5.52830856 3.99684275]
 [4.69503385 